db:
  type: sqlite3
  sqlite3:
    dsn: "file::memory:?cache=shared"
  mysql:
    host: localhost
    port: 3306
    user: admin
    pass: password
    db_name: db_name
app:
  port: 8080
  auth_token_expire: 30m
