db:
  type: mysql
  auto_migrate: true
  sqlite3:
    dsn: "file::memory:?cache=shared"
  mysql:
    host: localhost
    port: 3306
    user: root
    pass: password
    db_name: hoyobar_test
sharding:
  user_shard_n: 8
app:
  port: 8080
  auth_token_expire: 10h
  check_user_is_author: true
  default_page_size: 20
  max_page_size: 20
