db:
  type: mysql
  auto_migrate: true
  sqlite3:
    dsn: "file::memory:?cache=shared"
  mysql:
    host: localhost
    port: 3306
    user: root
    pass: password
    db_name: hoyobar_test
redis:
  addr: localhost:6379
  username: ""
  password: ""
sharding:
  user_shard_n: 8
app:
  port: 8080
  check_user_is_author: true
  default_page_size: 20
  max_page_size: 20
  expire:
    # if possible, the real expire will add a random num from (-e*jitter, +e*jitter)
    jitter: 0.0
    auth_token: 10h
    user_info: 360h # 15 days
    post_info: 168h # 10 days
  timeout:
    default: 10s
